/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ajayk
 */
public class Zirboin extends javax.swing.JFrame {
    double amountTotal;
    
    double totalDrobzit;
    double totalClickwick;
    double totalGazoontight;
    double totalFrazoint;
    double totalBlointoint;
    double totalVrobit;
    
    final int DROBZIT = 100000;
    final int CLICKWICK = 50000;
    final int GAZOONTIGHT = 10000;
    final int FRAZOINT = 1000;
    final int BLOINTOINT = 500;
    final int VROBIT = 1;
    

    /**
     * Creates new form Zirboin
     */
    public Zirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Drozits_lbl = new javax.swing.JLabel();
        Enter_button = new javax.swing.JButton();
        Clickwicks_lbl = new javax.swing.JLabel();
        Calculate_lbl = new javax.swing.JLabel();
        Gazoontights_lbl = new javax.swing.JLabel();
        Drobzit_txt = new javax.swing.JTextField();
        Clickwick_txt = new javax.swing.JTextField();
        Gazoontight_txt = new javax.swing.JTextField();
        Frazoint_lbl = new javax.swing.JLabel();
        Title_lbl = new javax.swing.JLabel();
        Frazoint_txt = new javax.swing.JTextField();
        TotalAmount_lbl = new javax.swing.JLabel();
        Blointoint_lbl = new javax.swing.JLabel();
        Total_txt = new javax.swing.JTextField();
        Blointoint_txt = new javax.swing.JTextField();
        Vrobit_lbl = new javax.swing.JLabel();
        Vrobit_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Drozits_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Drozits_lbl.setText("Total Drobzits Needed:");

        Enter_button.setText("Enter");
        Enter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_buttonActionPerformed(evt);
            }
        });

        Clickwicks_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Clickwicks_lbl.setText("Total Clickwicks Needed:");

        Calculate_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Calculate_lbl.setText("Calculate:");

        Gazoontights_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Gazoontights_lbl.setText("Total Gazoontights Needed:");

        Drobzit_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N

        Clickwick_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N

        Gazoontight_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N

        Frazoint_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Frazoint_lbl.setText("Total Frazoint Needed:");

        Title_lbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 28)); // NOI18N
        Title_lbl.setText("ZirboinFinancial Calculator");

        Frazoint_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N
        Frazoint_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Frazoint_txtActionPerformed(evt);
            }
        });

        TotalAmount_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        TotalAmount_lbl.setText("Enter the total amount you want to convert:");

        Blointoint_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Blointoint_lbl.setText("Total Blointoints Needed:");

        Total_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N

        Blointoint_txt.setFont(new java.awt.Font("Mongolian Baiti", 0, 16)); // NOI18N

        Vrobit_lbl.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N
        Vrobit_lbl.setText("Total Vrobits Needed:");

        Vrobit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vrobit_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalAmount_lbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Drozits_lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(Drobzit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Frazoint_lbl))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(Clickwick_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(Gazoontight_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Clickwicks_lbl)
                                    .addComponent(Blointoint_lbl))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gazoontights_lbl)
                                    .addComponent(Vrobit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title_lbl)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Enter_button)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Frazoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(161, 161, 161)
                            .addComponent(Blointoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(Calculate_lbl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Vrobit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalAmount_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drozits_lbl)
                    .addComponent(Clickwicks_lbl)
                    .addComponent(Gazoontights_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drobzit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clickwick_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gazoontight_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Frazoint_lbl)
                    .addComponent(Blointoint_lbl)
                    .addComponent(Vrobit_lbl))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Frazoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blointoint_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vrobit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Calculate_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enter_button)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Frazoint_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Frazoint_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Frazoint_txtActionPerformed

    private void Enter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_buttonActionPerformed
        //Get Total Amount
            amountTotal = Double.parseDouble(Total_txt.getText()); 
        
        //DrobzitamountTotal
            totalDrobzit = amountTotal / DROBZIT;
            totalDrobzit = (int) Math.floor(totalDrobzit);
            Drobzit_txt.setText(String.valueOf(totalDrobzit));
            amountTotal = amountTotal % DROBZIT;
        //Clickwick
            totalClickwick = amountTotal / CLICKWICK;
            totalClickwick = (int) Math.floor(totalClickwick);    
            Clickwick_txt.setText(String.valueOf(totalClickwick));
            amountTotal = amountTotal % CLICKWICK;
            
        //Gazoontight
             totalGazoontight = amountTotal / GAZOONTIGHT;
             totalGazoontight = (int) Math.floor(totalGazoontight);
             Gazoontight_txt.setText(String.valueOf(totalGazoontight));
             amountTotal = amountTotal % GAZOONTIGHT;  
     
        //Frazoint     
             totalFrazoint = amountTotal / FRAZOINT;
             totalFrazoint = (int) Math.floor(totalFrazoint);    
             Frazoint_txt.setText(String.valueOf(totalFrazoint));
             amountTotal = amountTotal % FRAZOINT; 
     
        //Blointoint     
             totalBlointoint = amountTotal / BLOINTOINT;
             totalBlointoint = (int) Math.floor(totalBlointoint);    
             Blointoint_txt.setText(String.valueOf(totalBlointoint));
             amountTotal = amountTotal % BLOINTOINT;   
      
        //Vrobit     
             totalVrobit = amountTotal / VROBIT;
             totalVrobit = (int) Math.floor(totalVrobit);
             Vrobit_txt.setText(String.valueOf(totalVrobit));
             amountTotal = amountTotal % VROBIT;
                
        
        
    }//GEN-LAST:event_Enter_buttonActionPerformed

    private void Vrobit_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vrobit_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vrobit_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blointoint_lbl;
    private javax.swing.JTextField Blointoint_txt;
    private javax.swing.JLabel Calculate_lbl;
    private javax.swing.JTextField Clickwick_txt;
    private javax.swing.JLabel Clickwicks_lbl;
    private javax.swing.JTextField Drobzit_txt;
    private javax.swing.JLabel Drozits_lbl;
    private javax.swing.JButton Enter_button;
    private javax.swing.JLabel Frazoint_lbl;
    private javax.swing.JTextField Frazoint_txt;
    private javax.swing.JTextField Gazoontight_txt;
    private javax.swing.JLabel Gazoontights_lbl;
    private javax.swing.JLabel Title_lbl;
    private javax.swing.JLabel TotalAmount_lbl;
    private javax.swing.JTextField Total_txt;
    private javax.swing.JLabel Vrobit_lbl;
    private javax.swing.JTextField Vrobit_txt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
